stages:
    - build
build_and_test:
    stage: build
    image: alpine:3.5
    tags:
        - shared
    script:
        - mvn clean install
    artifacts:
        name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
        paths:
            - openidm-zip/target/openidm-*.zip
